recipe/urls.py
from django.urls import path
from .views import home, RecipeListView, RecipeDetailView, search_view, create_view

app_name = 'recipe'

urlpatterns = [
    path('', home, name='home'),
    path("recipes/", RecipeListView.as_view(), name="recipe_list"),
    path("recipes/<pk>", RecipeDetailView.as_view(), name="recipe_detail"),
    path("search/", search_view, name='search'),
    path("create/", create_view, name='create'),
]

recipe_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import login_view, logout_view, logout_success

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipe.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('logout/success', logout_success, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.


class Recipe(models.Model):
    name = models.CharField(max_length=120)
    # positive integer only
    cooking_time = models.PositiveIntegerField(help_text='in mins')
    ingredients = models.CharField(
        max_length=255, help_text='separate ingredient by a comma & a space')
    description = models.TextField()
    # added in pic field for recipe
    # gives user better idea of what kind of food it is
    pic = models.ImageField(upload_to='recipe', default='no_picture.jpg')

    def calculate_difficulty(self):
        ingredients = self.ingredients.split(', ')
        if self.cooking_time < 10 and len(ingredients) < 4:
            difficulty = 'Easy'
        elif self.cooking_time < 10 and len(ingredients) >= 4:
            difficulty = 'Medium'
        elif self.cooking_time >= 10 and len(ingredients) < 4:
            difficulty = 'Intermediate'
        elif self.cooking_time >= 10 and len(ingredients) >= 4:
            difficulty = 'Hard'
        return difficulty

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse('recipe:recipe_detail', kwargs={'pk': self.pk})

user/models.py
from django.db import models

# Create your models here.

# define user class


class User(models.Model):
    # username, max length 20 char
    username = models.CharField(max_length=20)
    # password, max length 20 char
    password = models.CharField(max_length=20)

    # string representation by username
    def __str__(self):
        return str(self.username)

recipe/forms.py
from django import forms
from django.shortcuts import render
from .models import Recipe

CHART__CHOICES = (
    ('#1', 'Bar chart'),
    ('#2', 'Pie chart'),
    ('#3', 'Line chart')
)

DIFF__CHOICES = (
    ('#1', 'Easy'),
    ('#2', 'Medium'),
    ('#3', 'Intermediate'),
    ('#4', 'Hard'),

)

# class-based Form


class RecipeSearchForm(forms.Form):
    recipe_diff = forms.ChoiceField(choices=DIFF__CHOICES)
    chart_type = forms.ChoiceField(choices=CHART__CHOICES)

class CreateRecipeForm(forms.Form):
    name = forms.CharField(max_length=50)
    cooking_time = forms.IntegerField(help_text='in mins')
    ingredients = forms.CharField(max_length=300, help_text='Separate by a comma and a space')
    

recipe/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView  # to display lists
from .models import Recipe  # to access book model
# to protect class-based view
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import RecipeSearchForm, CreateRecipeForm
from .utils import get_recipename_from_id, get_chart

import pandas as pd

# Create views here

# define homepage function
# function takes request from web app
# returns template at recipes/home.html as response


def home(request):
    return render(request, 'recipe/recipe_home.html')


class RecipeListView(LoginRequiredMixin, ListView):
    model = Recipe  # specify model
    template_name = 'recipe/recipe_list.html'  # specify template


class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = 'recipe/recipe_detail.html'

def create_view(request):
    form = CreateRecipeForm(request.POST or None)
    name = None
    cooking_time = None
    ingredients = None

    if request.method == 'POST':
        try:
            recipe = Recipe.objects.create(
                name = request.POST.get('name'),
                cooking_time = request.POST.get('cooking_time'),
                ingredients = request.POST.get('ingredients'),
            )

            recipe.save()
        except:
            print('Error in creating recipe.')
    
    context = {
        'form': form,
        'name': name,
        'cooking_time': cooking_time,
        'ingredients': ingredients
    }

    return render(request, 'recipe/recipe_create.html', context)

def search_view(request):
    form = RecipeSearchForm(request.POST or None)
    recipe_df = None  # initialize dataframe to None
    recipe_diff = None
    chart = None
    qs = None

    if request.method == 'POST':
        recipe_diff = request.POST.get('recipe_diff')
        chart_type = request.POST.get('chart_type')

        if recipe_diff == '#1':
            recipe_diff = 'Easy'
        elif recipe_diff == '#2':
            recipe_diff = 'Medium'
        elif recipe_diff == '#3':
            recipe_diff = 'Intermediate'
        elif recipe_diff == '#4':
            recipe_diff = 'Hard'

        qs = Recipe.objects.all()
        id_searched = []
        for obj in qs:
            diff = obj.calculate_difficulty()
            if diff == recipe_diff:
                id_searched.append(obj.id)

        qs = qs.filter(id__in=id_searched)

        if qs:
            recipe_df = pd.DataFrame(qs.values())
            chart = get_chart(chart_type, recipe_df,
                              labels=recipe_df['name'].values)

            recipe_df = recipe_df.to_html()

    context = {
        'form': form,
        'recipe_df': recipe_df,
        'recipe_diff': recipe_diff,
        'chart': chart,
        'qs': qs
    }

    return render(request, 'recipe/search.html', context)

recipe_project/views.py
from django.shortcuts import render, redirect

# django authentication libraries
from django.contrib.auth import authenticate, login, logout
# django form for auth
from django.contrib.auth.forms import AuthenticationForm


# function to login


def login_view(request):
    error_message = None
    # Create form object
    form = AuthenticationForm()

    # when user hits login button and generates POST request
    if request.method == 'POST':
        # read data sent by form via POST
        form = AuthenticationForm(data=request.POST)

    # check if form is valid
    if form.is_valid():
        username = form.cleaned_data.get('username')  # read username
        password = form.cleaned_data.get('password')  # read password

    # use Django authenticate function to validate user
        user = authenticate(username=username, password=password)
    # user authenticated
        if user is not None:
            # login user
            login(request, user)
        # send user to desired page
            return redirect('recipe:recipe_list')
        else:
            error_message = 'Something went wrong'

    # prepare data to send from view to template
    context = {
        'form': form,  # send form data
        'error_message': error_message  # send error message
    }

    # load the login page
    return render(request, 'auth/login.html', context)


# function to logout
def logout_view(request):
    logout(request)
    return redirect('logout_success')


def logout_success(request):
    return render(request, 'auth/success.html')

user/views.py
from django.shortcuts import render

# Create your views here.

recipe/templates/recipe/recipe_create.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Create Recipe</title>
</head>
<h1>Create Recipe</h1>

<body>
    <div style="float:right;">
        <a href="{%url 'recipe:recipe_list' %}">Recipe List</a>
        <a href="{%url 'recipe:create'%}">Create recipe</a>
        <a href="{%url 'recipe:search' %}">Search</a>
        <a href="{%url 'logout' %}"> Logout </a>
    </div><br>
</body>


<form action="" method="POST">
    {%csrf_token%}
    {{form.as_p}}
    <button type="submit">Create Recipe</button>

</form>

</html>

recipe/templates/recipe/recipe_detail.html
<!DOCTYPE html>
<html>
<h1>Details:</h1>

<a href="{%url 'recipe:recipe_list' %}">Recipe List</a>
<a href="{%url 'recipe:create'%}">Create recipe</a>
<a href="{%url 'recipe:search' %}">Search</a>
<a href="{%url 'logout' %}"> Logout </a>

<head>
    <title>Details</title>
    <style>
        table {
            margin-left: auto;
            margin-right: auto;
            text-align: center;
        }

        img {
            margin-left: auto;
            margin-right: auto;
            width: 300px;
            height: 200px;
            border-radius: 20px;
            padding: 5px;
            display: block;
        }
    </style>
</head>

<body>
    <div>
        <h2 style="text-align: center;">Recipe: {{object.name}}</h2>
        <table border="1" cellpadding="3" cellspacing="3">
            <tr>
                <td><b>Description</b></td>
                <td>{{object.description}}</td>
            </tr>
            <tr>
                <td><b>Difficulty</b></td>
                <td>{{object.calculate_difficulty}}</td>
            </tr>
            <tr>
                <td><b>Cooking time</b></td>
                <td>{{object.cooking_time}} mins</td>
            </tr>
            <tr>
                <td><b>Ingredients</b></td>
                <td>{{object.ingredients}}</td>
            </tr>
        </table>
        <p><img src="{{object.pic.url}}"></p>

        <a href="/recipes/">Back: View all Recipes</a>

    </div>
</body>

</html>

recipe/templates/recipe/recipe_home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="static/style.css">
    <title>
        Recipe-App
    </title>
</head>

<body>
    <h1>Welcome to Recipe-App!</h1>
    <br>

    <div style="position:relative">
        <center>
            <img src="{% static 'recipe/images/recipe-bg.jpg' %}" alt="home" width="80%">
            <a href="/login/" style="position:absolute; left: 500px; top: 250px; text-align:center">Login
            </a>
        </center>
    </div>


</body>

</html>

recipe/templates/recipe/recipe_list.html
{% load static %}

<!DOCTYPE html>
<h1 style="text-align: center;">Recipes' List</h1>


<div style="float: right;">
    <a href="{%url 'recipe:recipe_list' %}">Recipe List</a>
    <a href="{%url 'recipe:create'%}">Create recipe</a>
    <a href="{%url 'recipe:search' %}">Search</a>
    <a href="{%url 'logout' %}"> Logout </a>
</div><br>

<head>
    <style>
        table,
        th,
        td {
            margin-left: auto;
            margin-right: auto;
            text-align: center;
        }

        .table-title {
            font-weight: bold;
            color: brown;
        }

        img {
            border-radius: 20px;
            padding: 5px;
        }
    </style>
</head>

<body>
    <table border="1" cellpadding="5" cellspacing="5">
        <tr class="table-title">
            <td>Image</td>
            <td>Name</td>
            <td>Description</td>
        </tr>
        {% for object in object_list %}
        <tr>
            <td><img src="{{object.pic.url}}" width="200" height="200" /></td>
            <td><a href="{{object.get_absolute_url}}">{{object.name}}</a></td>
            <td>{{object.description}}</td>

        </tr>

        {% endfor %}
    </table>
</body>

recipe/templates/recipe/search.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Recipe Search</title>
</head>

<body>
    <div>
        <a href="{%url 'recipe:recipe_list' %}">Recipe List</a>
        <a href="{%url 'recipe:create'%}">Create recipe</a>
        <a href="{%url 'recipe:search' %}">Search</a>
        <a href="{%url 'logout' %}"> Logout </a>
    </div>
    <hr>
    <h1> Search for recipe records </h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{form}}
        <button type="submit">Search</button>
    </form>

    {% if recipe_df %}
    {{recipe_df|safe}}
    <br>
    <img src="data:image/png;base64, {{chart|safe}}">
    {% else %}
    <h3> no data</h3>
    {% endif %}
</body>

</html>